// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/analysis.dart';
import 'api/genoz.dart';
import 'api/memory.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CompareEvent> dco_decode_StreamSink_compare_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ImportEvent> dco_decode_StreamSink_import_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CompareSide dco_decode_box_autoadd_compare_side(dynamic raw);

  @protected
  MemorySide dco_decode_box_autoadd_memory_side(dynamic raw);

  @protected
  CompareEvent dco_decode_compare_event(dynamic raw);

  @protected
  CompareOutputs dco_decode_compare_outputs(dynamic raw);

  @protected
  CompareSide dco_decode_compare_side(dynamic raw);

  @protected
  ExportedBytes dco_decode_exported_bytes(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImportEvent dco_decode_import_event(dynamic raw);

  @protected
  ImportPhase dco_decode_import_phase(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MemorySide dco_decode_memory_side(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CompareSide? dco_decode_opt_box_autoadd_compare_side(dynamic raw);

  @protected
  MemorySide? dco_decode_opt_box_autoadd_memory_side(dynamic raw);

  @protected
  ResultPage dco_decode_result_page(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CompareEvent> sse_decode_StreamSink_compare_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ImportEvent> sse_decode_StreamSink_import_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CompareSide sse_decode_box_autoadd_compare_side(SseDeserializer deserializer);

  @protected
  MemorySide sse_decode_box_autoadd_memory_side(SseDeserializer deserializer);

  @protected
  CompareEvent sse_decode_compare_event(SseDeserializer deserializer);

  @protected
  CompareOutputs sse_decode_compare_outputs(SseDeserializer deserializer);

  @protected
  CompareSide sse_decode_compare_side(SseDeserializer deserializer);

  @protected
  ExportedBytes sse_decode_exported_bytes(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImportEvent sse_decode_import_event(SseDeserializer deserializer);

  @protected
  ImportPhase sse_decode_import_phase(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MemorySide sse_decode_memory_side(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CompareSide? sse_decode_opt_box_autoadd_compare_side(
    SseDeserializer deserializer,
  );

  @protected
  MemorySide? sse_decode_opt_box_autoadd_memory_side(
    SseDeserializer deserializer,
  );

  @protected
  ResultPage sse_decode_result_page(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_compare_event_Sse(
    RustStreamSink<CompareEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_import_event_Sse(
    RustStreamSink<ImportEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compare_side(
    CompareSide self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_memory_side(
    MemorySide self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compare_event(CompareEvent self, SseSerializer serializer);

  @protected
  void sse_encode_compare_outputs(
    CompareOutputs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compare_side(CompareSide self, SseSerializer serializer);

  @protected
  void sse_encode_exported_bytes(ExportedBytes self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_import_event(ImportEvent self, SseSerializer serializer);

  @protected
  void sse_encode_import_phase(ImportPhase self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_side(MemorySide self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_compare_side(
    CompareSide? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_memory_side(
    MemorySide? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_result_page(ResultPage self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
