// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/analysis.dart';
import 'api/genoz.dart';
import 'api/memory.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiGenozInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 581572737;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'genoz_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiGenozCancelJob({required String jobId});

  Future<CompareOutputs> crateApiMemoryCompareBytes({
    required MemorySide a,
    required MemorySide b,
    required String optionsJson,
    required String createdAt,
  });

  Stream<CompareEvent> crateApiAnalysisCompareFiles({
    required CompareSide a,
    required CompareSide b,
    required String optionsJson,
    required String outDir,
    required String createdAt,
    required String jobId,
  });

  String crateApiGenozCoreVersion();

  Future<ExportedBytes> crateApiMemoryExportLoaded({
    required String key,
    required String filterJson,
    required String format,
    required String sampleA,
    required String sampleB,
  });

  Future<BigInt> crateApiAnalysisExportRows({
    required String outDir,
    required String filterJson,
    required String format,
    required String sampleA,
    required String sampleB,
    required String destPath,
  });

  void crateApiAnalysisForgetResult({required String outDir});

  Stream<ImportEvent> crateApiGenozImportVcf({
    required String sourcePath,
    required String destPath,
    required String jobId,
  });

  Future<void> crateApiGenozInitApp();

  Future<String> crateApiMemoryInspectBytes({required List<int> data});

  String? crateApiAnalysisParseRegion({required String text});

  Future<String> crateApiAnalysisResultDensity({
    required String outDir,
    required String filterJson,
    required BigInt binSize,
  });

  Future<String> crateApiMemoryResultDensityLoaded({
    required String key,
    required String filterJson,
    required BigInt binSize,
  });

  bool crateApiMemoryResultIsLoaded({required String key});

  Future<void> crateApiMemoryResultLoad({
    required String key,
    required List<int> rowsBgz,
    required List<int> rowsIdx,
  });

  Future<ResultPage> crateApiAnalysisResultPage({
    required String outDir,
    required String filterJson,
    required int start,
    required int count,
  });

  Future<ResultPage> crateApiMemoryResultPageLoaded({
    required String key,
    required String filterJson,
    required int start,
    required int count,
  });

  void crateApiMemoryResultUnload({required String key});

  Future<Uint8List> crateApiMemorySyntheticBytes({
    required BigInt seed,
    required int samples,
    required int variantsPerChrom,
  });

  Future<void> crateApiGenozWriteSyntheticExample({
    required String destPath,
    required BigInt seed,
    required int samples,
    required int variantsPerChrom,
    required bool grch37,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiGenozCancelJob({required String jobId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(jobId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenozCancelJobConstMeta,
        argValues: [jobId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenozCancelJobConstMeta =>
      const TaskConstMeta(debugName: "cancel_job", argNames: ["jobId"]);

  @override
  Future<CompareOutputs> crateApiMemoryCompareBytes({
    required MemorySide a,
    required MemorySide b,
    required String optionsJson,
    required String createdAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_memory_side(a, serializer);
          sse_encode_box_autoadd_memory_side(b, serializer);
          sse_encode_String(optionsJson, serializer);
          sse_encode_String(createdAt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_compare_outputs,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemoryCompareBytesConstMeta,
        argValues: [a, b, optionsJson, createdAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryCompareBytesConstMeta => const TaskConstMeta(
    debugName: "compare_bytes",
    argNames: ["a", "b", "optionsJson", "createdAt"],
  );

  @override
  Stream<CompareEvent> crateApiAnalysisCompareFiles({
    required CompareSide a,
    required CompareSide b,
    required String optionsJson,
    required String outDir,
    required String createdAt,
    required String jobId,
  }) {
    final sink = RustStreamSink<CompareEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_box_autoadd_compare_side(a, serializer);
            sse_encode_box_autoadd_compare_side(b, serializer);
            sse_encode_String(optionsJson, serializer);
            sse_encode_String(outDir, serializer);
            sse_encode_String(createdAt, serializer);
            sse_encode_String(jobId, serializer);
            sse_encode_StreamSink_compare_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAnalysisCompareFilesConstMeta,
          argValues: [a, b, optionsJson, outDir, createdAt, jobId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAnalysisCompareFilesConstMeta =>
      const TaskConstMeta(
        debugName: "compare_files",
        argNames: [
          "a",
          "b",
          "optionsJson",
          "outDir",
          "createdAt",
          "jobId",
          "sink",
        ],
      );

  @override
  String crateApiGenozCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenozCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenozCoreVersionConstMeta =>
      const TaskConstMeta(debugName: "core_version", argNames: []);

  @override
  Future<ExportedBytes> crateApiMemoryExportLoaded({
    required String key,
    required String filterJson,
    required String format,
    required String sampleA,
    required String sampleB,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_String(format, serializer);
          sse_encode_String(sampleA, serializer);
          sse_encode_String(sampleB, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_exported_bytes,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemoryExportLoadedConstMeta,
        argValues: [key, filterJson, format, sampleA, sampleB],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryExportLoadedConstMeta => const TaskConstMeta(
    debugName: "export_loaded",
    argNames: ["key", "filterJson", "format", "sampleA", "sampleB"],
  );

  @override
  Future<BigInt> crateApiAnalysisExportRows({
    required String outDir,
    required String filterJson,
    required String format,
    required String sampleA,
    required String sampleB,
    required String destPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outDir, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_String(format, serializer);
          sse_encode_String(sampleA, serializer);
          sse_encode_String(sampleB, serializer);
          sse_encode_String(destPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAnalysisExportRowsConstMeta,
        argValues: [outDir, filterJson, format, sampleA, sampleB, destPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisExportRowsConstMeta => const TaskConstMeta(
    debugName: "export_rows",
    argNames: [
      "outDir",
      "filterJson",
      "format",
      "sampleA",
      "sampleB",
      "destPath",
    ],
  );

  @override
  void crateApiAnalysisForgetResult({required String outDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisForgetResultConstMeta,
        argValues: [outDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisForgetResultConstMeta =>
      const TaskConstMeta(debugName: "forget_result", argNames: ["outDir"]);

  @override
  Stream<ImportEvent> crateApiGenozImportVcf({
    required String sourcePath,
    required String destPath,
    required String jobId,
  }) {
    final sink = RustStreamSink<ImportEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sourcePath, serializer);
            sse_encode_String(destPath, serializer);
            sse_encode_String(jobId, serializer);
            sse_encode_StreamSink_import_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiGenozImportVcfConstMeta,
          argValues: [sourcePath, destPath, jobId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiGenozImportVcfConstMeta => const TaskConstMeta(
    debugName: "import_vcf",
    argNames: ["sourcePath", "destPath", "jobId", "sink"],
  );

  @override
  Future<void> crateApiGenozInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenozInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenozInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiMemoryInspectBytes({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemoryInspectBytesConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryInspectBytesConstMeta =>
      const TaskConstMeta(debugName: "inspect_bytes", argNames: ["data"]);

  @override
  String? crateApiAnalysisParseRegion({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisParseRegionConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisParseRegionConstMeta =>
      const TaskConstMeta(debugName: "parse_region", argNames: ["text"]);

  @override
  Future<String> crateApiAnalysisResultDensity({
    required String outDir,
    required String filterJson,
    required BigInt binSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outDir, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_u_64(binSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAnalysisResultDensityConstMeta,
        argValues: [outDir, filterJson, binSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisResultDensityConstMeta =>
      const TaskConstMeta(
        debugName: "result_density",
        argNames: ["outDir", "filterJson", "binSize"],
      );

  @override
  Future<String> crateApiMemoryResultDensityLoaded({
    required String key,
    required String filterJson,
    required BigInt binSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_u_64(binSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemoryResultDensityLoadedConstMeta,
        argValues: [key, filterJson, binSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryResultDensityLoadedConstMeta =>
      const TaskConstMeta(
        debugName: "result_density_loaded",
        argNames: ["key", "filterJson", "binSize"],
      );

  @override
  bool crateApiMemoryResultIsLoaded({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryResultIsLoadedConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryResultIsLoadedConstMeta =>
      const TaskConstMeta(debugName: "result_is_loaded", argNames: ["key"]);

  @override
  Future<void> crateApiMemoryResultLoad({
    required String key,
    required List<int> rowsBgz,
    required List<int> rowsIdx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_list_prim_u_8_loose(rowsBgz, serializer);
          sse_encode_list_prim_u_8_loose(rowsIdx, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemoryResultLoadConstMeta,
        argValues: [key, rowsBgz, rowsIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryResultLoadConstMeta => const TaskConstMeta(
    debugName: "result_load",
    argNames: ["key", "rowsBgz", "rowsIdx"],
  );

  @override
  Future<ResultPage> crateApiAnalysisResultPage({
    required String outDir,
    required String filterJson,
    required int start,
    required int count,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outDir, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_u_32(start, serializer);
          sse_encode_u_32(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_result_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAnalysisResultPageConstMeta,
        argValues: [outDir, filterJson, start, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisResultPageConstMeta => const TaskConstMeta(
    debugName: "result_page",
    argNames: ["outDir", "filterJson", "start", "count"],
  );

  @override
  Future<ResultPage> crateApiMemoryResultPageLoaded({
    required String key,
    required String filterJson,
    required int start,
    required int count,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(filterJson, serializer);
          sse_encode_u_32(start, serializer);
          sse_encode_u_32(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_result_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemoryResultPageLoadedConstMeta,
        argValues: [key, filterJson, start, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryResultPageLoadedConstMeta =>
      const TaskConstMeta(
        debugName: "result_page_loaded",
        argNames: ["key", "filterJson", "start", "count"],
      );

  @override
  void crateApiMemoryResultUnload({required String key}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryResultUnloadConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryResultUnloadConstMeta =>
      const TaskConstMeta(debugName: "result_unload", argNames: ["key"]);

  @override
  Future<Uint8List> crateApiMemorySyntheticBytes({
    required BigInt seed,
    required int samples,
    required int variantsPerChrom,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(seed, serializer);
          sse_encode_u_32(samples, serializer);
          sse_encode_u_32(variantsPerChrom, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMemorySyntheticBytesConstMeta,
        argValues: [seed, samples, variantsPerChrom],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemorySyntheticBytesConstMeta =>
      const TaskConstMeta(
        debugName: "synthetic_bytes",
        argNames: ["seed", "samples", "variantsPerChrom"],
      );

  @override
  Future<void> crateApiGenozWriteSyntheticExample({
    required String destPath,
    required BigInt seed,
    required int samples,
    required int variantsPerChrom,
    required bool grch37,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(destPath, serializer);
          sse_encode_u_64(seed, serializer);
          sse_encode_u_32(samples, serializer);
          sse_encode_u_32(variantsPerChrom, serializer);
          sse_encode_bool(grch37, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenozWriteSyntheticExampleConstMeta,
        argValues: [destPath, seed, samples, variantsPerChrom, grch37],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenozWriteSyntheticExampleConstMeta =>
      const TaskConstMeta(
        debugName: "write_synthetic_example",
        argNames: ["destPath", "seed", "samples", "variantsPerChrom", "grch37"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<CompareEvent> dco_decode_StreamSink_compare_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ImportEvent> dco_decode_StreamSink_import_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CompareSide dco_decode_box_autoadd_compare_side(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_compare_side(raw);
  }

  @protected
  MemorySide dco_decode_box_autoadd_memory_side(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_memory_side(raw);
  }

  @protected
  CompareEvent dco_decode_compare_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CompareEvent_Progress(
          bytesDone: dco_decode_u_64(raw[1]),
          bytesTotal: dco_decode_u_64(raw[2]),
        );
      case 1:
        return CompareEvent_Done(
          summaryJson: dco_decode_String(raw[1]),
          manifestJson: dco_decode_String(raw[2]),
        );
      case 2:
        return CompareEvent_Failed(message: dco_decode_String(raw[1]));
      case 3:
        return CompareEvent_Cancelled();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  CompareOutputs dco_decode_compare_outputs(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CompareOutputs(
      rowsBgz: dco_decode_list_prim_u_8_strict(arr[0]),
      rowsIdx: dco_decode_list_prim_u_8_strict(arr[1]),
      summaryJson: dco_decode_String(arr[2]),
      statsAJson: dco_decode_String(arr[3]),
      statsBJson: dco_decode_String(arr[4]),
      manifestJson: dco_decode_String(arr[5]),
    );
  }

  @protected
  CompareSide dco_decode_compare_side(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return CompareSide(
      path: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      sha256: dco_decode_String(arr[2]),
      bytes: dco_decode_u_64(arr[3]),
      sample: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  ExportedBytes dco_decode_exported_bytes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExportedBytes(
      data: dco_decode_list_prim_u_8_strict(arr[0]),
      rows: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImportEvent dco_decode_import_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return ImportEvent_Progress(
          phase: dco_decode_import_phase(raw[1]),
          bytesDone: dco_decode_u_64(raw[2]),
          bytesTotal: dco_decode_u_64(raw[3]),
        );
      case 1:
        return ImportEvent_Done(reportJson: dco_decode_String(raw[1]));
      case 2:
        return ImportEvent_Failed(message: dco_decode_String(raw[1]));
      case 3:
        return ImportEvent_Cancelled();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ImportPhase dco_decode_import_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImportPhase.values[raw as int];
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MemorySide dco_decode_memory_side(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MemorySide(
      displayName: dco_decode_String(arr[0]),
      sha256: dco_decode_String(arr[1]),
      sample: dco_decode_opt_String(arr[2]),
      data: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ResultPage dco_decode_result_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ResultPage(
      total: dco_decode_u_32(arr[0]),
      rowsJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<CompareEvent> sse_decode_StreamSink_compare_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ImportEvent> sse_decode_StreamSink_import_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CompareSide sse_decode_box_autoadd_compare_side(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_compare_side(deserializer));
  }

  @protected
  MemorySide sse_decode_box_autoadd_memory_side(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_memory_side(deserializer));
  }

  @protected
  CompareEvent sse_decode_compare_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_bytesDone = sse_decode_u_64(deserializer);
        var var_bytesTotal = sse_decode_u_64(deserializer);
        return CompareEvent_Progress(
          bytesDone: var_bytesDone,
          bytesTotal: var_bytesTotal,
        );
      case 1:
        var var_summaryJson = sse_decode_String(deserializer);
        var var_manifestJson = sse_decode_String(deserializer);
        return CompareEvent_Done(
          summaryJson: var_summaryJson,
          manifestJson: var_manifestJson,
        );
      case 2:
        var var_message = sse_decode_String(deserializer);
        return CompareEvent_Failed(message: var_message);
      case 3:
        return CompareEvent_Cancelled();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  CompareOutputs sse_decode_compare_outputs(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_rowsBgz = sse_decode_list_prim_u_8_strict(deserializer);
    var var_rowsIdx = sse_decode_list_prim_u_8_strict(deserializer);
    var var_summaryJson = sse_decode_String(deserializer);
    var var_statsAJson = sse_decode_String(deserializer);
    var var_statsBJson = sse_decode_String(deserializer);
    var var_manifestJson = sse_decode_String(deserializer);
    return CompareOutputs(
      rowsBgz: var_rowsBgz,
      rowsIdx: var_rowsIdx,
      summaryJson: var_summaryJson,
      statsAJson: var_statsAJson,
      statsBJson: var_statsBJson,
      manifestJson: var_manifestJson,
    );
  }

  @protected
  CompareSide sse_decode_compare_side(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    var var_sample = sse_decode_opt_String(deserializer);
    return CompareSide(
      path: var_path,
      displayName: var_displayName,
      sha256: var_sha256,
      bytes: var_bytes,
      sample: var_sample,
    );
  }

  @protected
  ExportedBytes sse_decode_exported_bytes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    var var_rows = sse_decode_u_64(deserializer);
    return ExportedBytes(data: var_data, rows: var_rows);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImportEvent sse_decode_import_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_phase = sse_decode_import_phase(deserializer);
        var var_bytesDone = sse_decode_u_64(deserializer);
        var var_bytesTotal = sse_decode_u_64(deserializer);
        return ImportEvent_Progress(
          phase: var_phase,
          bytesDone: var_bytesDone,
          bytesTotal: var_bytesTotal,
        );
      case 1:
        var var_reportJson = sse_decode_String(deserializer);
        return ImportEvent_Done(reportJson: var_reportJson);
      case 2:
        var var_message = sse_decode_String(deserializer);
        return ImportEvent_Failed(message: var_message);
      case 3:
        return ImportEvent_Cancelled();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ImportPhase sse_decode_import_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImportPhase.values[inner];
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MemorySide sse_decode_memory_side(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_displayName = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    var var_sample = sse_decode_opt_String(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return MemorySide(
      displayName: var_displayName,
      sha256: var_sha256,
      sample: var_sample,
      data: var_data,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ResultPage sse_decode_result_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_total = sse_decode_u_32(deserializer);
    var var_rowsJson = sse_decode_String(deserializer);
    return ResultPage(total: var_total, rowsJson: var_rowsJson);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_compare_event_Sse(
    RustStreamSink<CompareEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_compare_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_import_event_Sse(
    RustStreamSink<ImportEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_import_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_compare_side(
    CompareSide self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_compare_side(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_memory_side(
    MemorySide self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_memory_side(self, serializer);
  }

  @protected
  void sse_encode_compare_event(CompareEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CompareEvent_Progress(
        bytesDone: final bytesDone,
        bytesTotal: final bytesTotal,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_64(bytesDone, serializer);
        sse_encode_u_64(bytesTotal, serializer);
      case CompareEvent_Done(
        summaryJson: final summaryJson,
        manifestJson: final manifestJson,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(summaryJson, serializer);
        sse_encode_String(manifestJson, serializer);
      case CompareEvent_Failed(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case CompareEvent_Cancelled():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_compare_outputs(
    CompareOutputs self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.rowsBgz, serializer);
    sse_encode_list_prim_u_8_strict(self.rowsIdx, serializer);
    sse_encode_String(self.summaryJson, serializer);
    sse_encode_String(self.statsAJson, serializer);
    sse_encode_String(self.statsBJson, serializer);
    sse_encode_String(self.manifestJson, serializer);
  }

  @protected
  void sse_encode_compare_side(CompareSide self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_u_64(self.bytes, serializer);
    sse_encode_opt_String(self.sample, serializer);
  }

  @protected
  void sse_encode_exported_bytes(ExportedBytes self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.data, serializer);
    sse_encode_u_64(self.rows, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_import_event(ImportEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case ImportEvent_Progress(
        phase: final phase,
        bytesDone: final bytesDone,
        bytesTotal: final bytesTotal,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_import_phase(phase, serializer);
        sse_encode_u_64(bytesDone, serializer);
        sse_encode_u_64(bytesTotal, serializer);
      case ImportEvent_Done(reportJson: final reportJson):
        sse_encode_i_32(1, serializer);
        sse_encode_String(reportJson, serializer);
      case ImportEvent_Failed(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case ImportEvent_Cancelled():
        sse_encode_i_32(3, serializer);
    }
  }

  @protected
  void sse_encode_import_phase(ImportPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_memory_side(MemorySide self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.sha256, serializer);
    sse_encode_opt_String(self.sample, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_result_page(ResultPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.total, serializer);
    sse_encode_String(self.rowsJson, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
