// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'analysis.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `matching`, `open_result`, `output_ref`, `parse_filter`, `run_compare`, `write_output`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CountingReader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `read`

/// Compara A × B e grava o resultado em `out_dir`. `options_json` segue
/// `genoz_core::compare::CompareOptions`. Em falha ou cancelamento a pasta é apagada.
Stream<CompareEvent> compareFiles({
  required CompareSide a,
  required CompareSide b,
  required String optionsJson,
  required String outDir,
  required String createdAt,
  required String jobId,
}) => RustLib.instance.api.crateApiAnalysisCompareFiles(
  a: a,
  b: b,
  optionsJson: optionsJson,
  outDir: outDir,
  createdAt: createdAt,
  jobId: jobId,
);

/// Página do resultado. Com filtro vazio (`{}`) lê direto pelo índice do arquivo;
/// com filtro, calcula uma vez as linhas que passam e guarda em cache.
Future<ResultPage> resultPage({
  required String outDir,
  required String filterJson,
  required int start,
  required int count,
}) => RustLib.instance.api.crateApiAnalysisResultPage(
  outDir: outDir,
  filterJson: filterJson,
  start: start,
  count: count,
);

/// Esquece os índices em cache de um resultado (ao apagar a análise).
void forgetResult({required String outDir}) =>
    RustLib.instance.api.crateApiAnalysisForgetResult(outDir: outDir);

/// Exporta as linhas filtradas (`csv`, `tsv`, `json` ou `vcf`) e copia o manifesto
/// da análise ao lado (`<destino>.manifest.json`). Retorna quantas linhas foram gravadas.
Future<BigInt> exportRows({
  required String outDir,
  required String filterJson,
  required String format,
  required String sampleA,
  required String sampleB,
  required String destPath,
}) => RustLib.instance.api.crateApiAnalysisExportRows(
  outDir: outDir,
  filterJson: filterJson,
  format: format,
  sampleA: sampleA,
  sampleB: sampleB,
  destPath: destPath,
);

/// Interpreta uma região digitada (`chr7:117.5M-117.6M`, `chr1:1000`, `X`).
/// Devolve JSON `{chrom,start,end}` ou `None` se o texto não for uma região.
String? parseRegion({required String text}) =>
    RustLib.instance.api.crateApiAnalysisParseRegion(text: text);

@freezed
sealed class CompareEvent with _$CompareEvent {
  const CompareEvent._();

  const factory CompareEvent.progress({
    required BigInt bytesDone,
    required BigInt bytesTotal,
  }) = CompareEvent_Progress;

  /// Resumo e manifesto em JSON (mesmo formato do `genoz-cli compare`).
  const factory CompareEvent.done({
    required String summaryJson,
    required String manifestJson,
  }) = CompareEvent_Done;
  const factory CompareEvent.failed({required String message}) =
      CompareEvent_Failed;
  const factory CompareEvent.cancelled() = CompareEvent_Cancelled;
}

/// Uma das entradas da comparação, como o app a conhece.
class CompareSide {
  final String path;

  /// Nome do arquivo mostrado ao usuário (vai para o manifesto).
  final String displayName;

  /// SHA-256 já calculado na importação (evita reler o arquivo).
  final String sha256;
  final BigInt bytes;

  /// `None` = primeira amostra do arquivo.
  final String? sample;

  const CompareSide({
    required this.path,
    required this.displayName,
    required this.sha256,
    required this.bytes,
    this.sample,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      displayName.hashCode ^
      sha256.hashCode ^
      bytes.hashCode ^
      sample.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompareSide &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          displayName == other.displayName &&
          sha256 == other.sha256 &&
          bytes == other.bytes &&
          sample == other.sample;
}

class ResultPage {
  /// Total de linhas (com o filtro aplicado).
  final int total;

  /// Linhas da página em JSON (lista de `ComparisonRow`).
  final String rowsJson;

  const ResultPage({required this.total, required this.rowsJson});

  @override
  int get hashCode => total.hashCode ^ rowsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResultPage &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          rowsJson == other.rowsJson;
}
