// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_any`, `forget`, `report`, `with_package`

/// Constrói um pacote a partir de um arquivo (`kind`: `gtf`, `clinvar` ou `custom`) e grava em `out_dir`.
Future<BuildReport> annotBuild({
  required String kind,
  required String inputPath,
  required String outDir,
  required String metaJson,
}) => RustLib.instance.api.crateApiAnnotationAnnotBuild(
  kind: kind,
  inputPath: inputPath,
  outDir: outDir,
  metaJson: metaJson,
);

Future<BuiltBytes> annotBuildBytes({
  required String kind,
  required List<int> data,
  required String metaJson,
}) => RustLib.instance.api.crateApiAnnotationAnnotBuildBytes(
  kind: kind,
  data: data,
  metaJson: metaJson,
);

/// SHA-256 de um arquivo (conferir um download do catálogo).
Future<String> sha256File({required String path}) =>
    RustLib.instance.api.crateApiAnnotationSha256File(path: path);

Future<String> sha256OfBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiAnnotationSha256OfBytes(data: data);

/// Esquece um pacote aberto (ao remover ou reinstalar).
void annotForget({required String key}) =>
    RustLib.instance.api.crateApiAnnotationAnnotForget(key: key);

/// Carrega um pacote na memória (Web), identificado por `key`.
Future<void> annotLoad({
  required String key,
  required List<int> manifestJson,
  required List<int> indexJson,
  required List<int> recordsBgz,
}) => RustLib.instance.api.crateApiAnnotationAnnotLoad(
  key: key,
  manifestJson: manifestJson,
  indexJson: indexJson,
  recordsBgz: recordsBgz,
);

bool annotIsLoaded({required String key}) =>
    RustLib.instance.api.crateApiAnnotationAnnotIsLoaded(key: key);

/// Anota linhas (`[{"chrom","pos","ref","alt"}]`) com os pacotes indicados (pastas ou chaves).
/// Devolve, para cada linha, os pacotes com algum registro e os registros.
Future<String> annotAnnotate({
  required List<String> packages,
  required String rowsJson,
}) => RustLib.instance.api.crateApiAnnotationAnnotAnnotate(
  packages: packages,
  rowsJson: rowsJson,
);

/// Procura um nome (ex.: gene) num pacote. Devolve os registros em JSON.
Future<String> annotFindName({required String package, required String name}) =>
    RustLib.instance.api.crateApiAnnotationAnnotFindName(
      package: package,
      name: name,
    );

/// Resultado da construção: manifesto + problemas (linhas ignoradas).
class BuildReport {
  final String manifestJson;
  final String issuesJson;
  final BigInt skipped;

  const BuildReport({
    required this.manifestJson,
    required this.issuesJson,
    required this.skipped,
  });

  @override
  int get hashCode =>
      manifestJson.hashCode ^ issuesJson.hashCode ^ skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildReport &&
          runtimeType == other.runtimeType &&
          manifestJson == other.manifestJson &&
          issuesJson == other.issuesJson &&
          skipped == other.skipped;
}

/// Pacote construído em memória (Web): o app grava os três arquivos onde quiser.
class BuiltBytes {
  final BuildReport report;
  final Uint8List recordsBgz;
  final Uint8List indexJson;

  const BuiltBytes({
    required this.report,
    required this.recordsBgz,
    required this.indexJson,
  });

  @override
  int get hashCode =>
      report.hashCode ^ recordsBgz.hashCode ^ indexJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuiltBytes &&
          runtimeType == other.runtimeType &&
          report == other.report &&
          recordsBgz == other.recordsBgz &&
          indexJson == other.indexJson;
}
