// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run`, `text`

/// Analisa um VCF multiamostra do disco e grava `familia.json` e `manifest.json` em `out_dir`.
Future<FamilyRun> familyAnalyzeFile({
  required String path,
  required String inputName,
  required String inputSha256,
  required BigInt inputBytes,
  required String optionsJson,
  required String outDir,
  required String createdAt,
}) => RustLib.instance.api.crateApiFamilyFamilyAnalyzeFile(
  path: path,
  inputName: inputName,
  inputSha256: inputSha256,
  inputBytes: inputBytes,
  optionsJson: optionsJson,
  outDir: outDir,
  createdAt: createdAt,
);

/// Web: o mesmo, na memória (o app grava os dois arquivos no OPFS).
Future<FamilyRun> familyAnalyzeBytes({
  required List<int> data,
  required String inputName,
  required String inputSha256,
  required String optionsJson,
  required String createdAt,
}) => RustLib.instance.api.crateApiFamilyFamilyAnalyzeBytes(
  data: data,
  inputName: inputName,
  inputSha256: inputSha256,
  optionsJson: optionsJson,
  createdAt: createdAt,
);

/// Família FICTÍCIA (VCF multiamostra, BGZF) para experimentar o módulo.
Future<Uint8List> syntheticFamilyBytes({required BigInt seed}) =>
    RustLib.instance.api.crateApiFamilySyntheticFamilyBytes(seed: seed);

/// Resultado (`familia.json`) e manifesto, em JSON.
class FamilyRun {
  final String resultJson;
  final String manifestJson;

  const FamilyRun({required this.resultJson, required this.manifestJson});

  @override
  int get hashCode => resultJson.hashCode ^ manifestJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FamilyRun &&
          runtimeType == other.runtimeType &&
          resultJson == other.resultJson &&
          manifestJson == other.manifestJson;
}
