// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'genoz.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `copy_and_hash`, `register`, `run_import`, `unregister`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Outcome`, `ProgressReader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `read`

/// Versão do núcleo científico (vai para os manifestos).
String coreVersion() => RustLib.instance.api.crateApiGenozCoreVersion();

/// Pede o cancelamento de uma importação em andamento.
void cancelJob({required String jobId}) =>
    RustLib.instance.api.crateApiGenozCancelJob(jobId: jobId);

/// Copia um VCF para a pasta privada do app (`dest_path`), calcula o SHA-256
/// e valida. Emite progresso; termina com `Done`, `Failed` ou `Cancelled`.
/// Em falha ou cancelamento, a cópia parcial é apagada.
Stream<ImportEvent> importVcf({
  required String sourcePath,
  required String destPath,
  required String jobId,
}) => RustLib.instance.api.crateApiGenozImportVcf(
  sourcePath: sourcePath,
  destPath: destPath,
  jobId: jobId,
);

/// Grava um VCF sintético (dados fictícios, BGZF) para experimentar o app sem arquivo real.
Future<void> writeSyntheticExample({
  required String destPath,
  required BigInt seed,
  required int samples,
  required int variantsPerChrom,
  required bool grch37,
}) => RustLib.instance.api.crateApiGenozWriteSyntheticExample(
  destPath: destPath,
  seed: seed,
  samples: samples,
  variantsPerChrom: variantsPerChrom,
  grch37: grch37,
);

@freezed
sealed class ImportEvent with _$ImportEvent {
  const ImportEvent._();

  const factory ImportEvent.progress({
    required ImportPhase phase,
    required BigInt bytesDone,
    required BigInt bytesTotal,
  }) = ImportEvent_Progress;

  /// Relatório de inspeção em JSON (o mesmo formato de `genoz-cli inspect --json`).
  const factory ImportEvent.done({required String reportJson}) =
      ImportEvent_Done;
  const factory ImportEvent.failed({required String message}) =
      ImportEvent_Failed;
  const factory ImportEvent.cancelled() = ImportEvent_Cancelled;
}

enum ImportPhase {
  /// Copiando para a pasta privada do app e calculando o SHA-256.
  copying,

  /// Lendo e validando o VCF.
  validating,
}
