// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'analysis.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `mem_key`, `output`, `reader_for`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SharedBytes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_ref`, `clone`

/// Inspeciona um VCF já em memória e devolve o relatório em JSON (com SHA-256).
Future<String> inspectBytes({required List<int> data}) =>
    RustLib.instance.api.crateApiMemoryInspectBytes(data: data);

/// Compara A × B em memória. Mesmo resultado (bytes) que `compare_files`.
Future<CompareOutputs> compareBytes({
  required MemorySide a,
  required MemorySide b,
  required String optionsJson,
  required String createdAt,
}) => RustLib.instance.api.crateApiMemoryCompareBytes(
  a: a,
  b: b,
  optionsJson: optionsJson,
  createdAt: createdAt,
);

/// Carrega `rows.bgz` + `rows.idx` de uma análise para paginar e exportar.
Future<void> resultLoad({
  required String key,
  required List<int> rowsBgz,
  required List<int> rowsIdx,
}) => RustLib.instance.api.crateApiMemoryResultLoad(
  key: key,
  rowsBgz: rowsBgz,
  rowsIdx: rowsIdx,
);

bool resultIsLoaded({required String key}) =>
    RustLib.instance.api.crateApiMemoryResultIsLoaded(key: key);

/// Libera a memória de um resultado carregado.
void resultUnload({required String key}) =>
    RustLib.instance.api.crateApiMemoryResultUnload(key: key);

/// Página de um resultado carregado (mesma lógica de `result_page`).
Future<ResultPage> resultPageLoaded({
  required String key,
  required String filterJson,
  required int start,
  required int count,
}) => RustLib.instance.api.crateApiMemoryResultPageLoaded(
  key: key,
  filterJson: filterJson,
  start: start,
  count: count,
);

/// Densidade de um resultado carregado (mesma lógica de `result_density`).
Future<String> resultDensityLoaded({
  required String key,
  required String filterJson,
  required BigInt binSize,
}) => RustLib.instance.api.crateApiMemoryResultDensityLoaded(
  key: key,
  filterJson: filterJson,
  binSize: binSize,
);

/// Exporta as linhas filtradas de um resultado carregado (`csv`, `tsv`, `json`, `vcf`).
Future<ExportedBytes> exportLoaded({
  required String key,
  required String filterJson,
  required String format,
  required String sampleA,
  required String sampleB,
}) => RustLib.instance.api.crateApiMemoryExportLoaded(
  key: key,
  filterJson: filterJson,
  format: format,
  sampleA: sampleA,
  sampleB: sampleB,
);

/// VCF sintético (BGZF) em memória — o mesmo de `write_synthetic_example`.
Future<Uint8List> syntheticBytes({
  required BigInt seed,
  required int samples,
  required int variantsPerChrom,
}) => RustLib.instance.api.crateApiMemorySyntheticBytes(
  seed: seed,
  samples: samples,
  variantsPerChrom: variantsPerChrom,
);

/// Todos os arquivos de uma análise, para o app gravar onde quiser (OPFS na Web).
class CompareOutputs {
  final Uint8List rowsBgz;
  final Uint8List rowsIdx;
  final String summaryJson;
  final String statsAJson;
  final String statsBJson;
  final String manifestJson;

  const CompareOutputs({
    required this.rowsBgz,
    required this.rowsIdx,
    required this.summaryJson,
    required this.statsAJson,
    required this.statsBJson,
    required this.manifestJson,
  });

  @override
  int get hashCode =>
      rowsBgz.hashCode ^
      rowsIdx.hashCode ^
      summaryJson.hashCode ^
      statsAJson.hashCode ^
      statsBJson.hashCode ^
      manifestJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompareOutputs &&
          runtimeType == other.runtimeType &&
          rowsBgz == other.rowsBgz &&
          rowsIdx == other.rowsIdx &&
          summaryJson == other.summaryJson &&
          statsAJson == other.statsAJson &&
          statsBJson == other.statsBJson &&
          manifestJson == other.manifestJson;
}

class ExportedBytes {
  final Uint8List data;
  final BigInt rows;

  const ExportedBytes({required this.data, required this.rows});

  @override
  int get hashCode => data.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportedBytes &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          rows == other.rows;
}

/// Um lado da comparação em memória.
class MemorySide {
  final String displayName;
  final String sha256;
  final String? sample;
  final Uint8List data;

  const MemorySide({
    required this.displayName,
    required this.sha256,
    this.sample,
    required this.data,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ sha256.hashCode ^ sample.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemorySide &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          sha256 == other.sha256 &&
          sample == other.sample &&
          data == other.data;
}
