// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `random32`, `vault_error`

/// Relatório de uma análise: HTML autocontido (`pdf = false`) ou PDF.
/// JSONs vazios = ausentes (análises antigas sem estatísticas).
Future<Uint8List> analysisReport({
  required String summaryJson,
  required String statsAJson,
  required String statsBJson,
  required String manifestJson,
  required String project,
  required String generatedAt,
  required String lang,
  required bool pdf,
}) => RustLib.instance.api.crateApiVaultAnalysisReport(
  summaryJson: summaryJson,
  statsAJson: statsAJson,
  statsBJson: statsBJson,
  manifestJson: manifestJson,
  project: project,
  generatedAt: generatedAt,
  lang: lang,
  pdf: pdf,
);

/// Cifra arquivos do disco num `.genoz` (em fluxo). Grava em `<out>.parcial` e renomeia
/// no fim: um arquivo pela metade nunca fica com o nome final. Devolve o tamanho.
Future<BigInt> vaultSealFiles({
  required List<PackBytes> inline,
  required List<PackFile> files,
  required String outPath,
  required String password,
  required List<int> random,
}) => RustLib.instance.api.crateApiVaultVaultSealFiles(
  inline: inline,
  files: files,
  outPath: outPath,
  password: password,
  random: random,
);

/// Abre um `.genoz` e extrai tudo em `out_dir` (que é apagada se der erro: nada pela metade).
/// Devolve os caminhos extraídos, na ordem do pacote.
Future<List<String>> vaultOpenToDir({
  required String inPath,
  required String password,
  required String outDir,
}) => RustLib.instance.api.crateApiVaultVaultOpenToDir(
  inPath: inPath,
  password: password,
  outDir: outDir,
);

/// Web: cifra arquivos na memória.
Future<Uint8List> vaultSealBytes({
  required List<PackBytes> entries,
  required String password,
  required List<int> random,
}) => RustLib.instance.api.crateApiVaultVaultSealBytes(
  entries: entries,
  password: password,
  random: random,
);

/// Web: abre um `.genoz` na memória.
Future<List<PackBytes>> vaultOpenBytes({
  required List<int> data,
  required String password,
}) => RustLib.instance.api.crateApiVaultVaultOpenBytes(
  data: data,
  password: password,
);

/// Um arquivo na memória (Web, e o projeto.json).
class PackBytes {
  final String path;
  final Uint8List data;

  const PackBytes({required this.path, required this.data});

  @override
  int get hashCode => path.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackBytes &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          data == other.data;
}

/// Um arquivo do disco que entra no pacote com o nome `path`.
class PackFile {
  final String path;
  final String sourcePath;

  const PackFile({required this.path, required this.sourcePath});

  @override
  int get hashCode => path.hashCode ^ sourcePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          sourcePath == other.sourcePath;
}
