"""Gera as fixtures FICTÍCIAS de arquivos de consumidor (Módulo 9).

Uma mesma "pessoa" inventada em quatro formatos de chip (23andMe, AncestryDNA,
MyHeritage, FamilyTreeDNA), um VCF GRCh37 de sequenciamento dela e um FASTA com
um trecho inventado do cromossomo 1 (as bases NÃO são do genoma humano real; só
precisam ser coerentes com o REF do VCF).

Uso:  python -X utf8 gerar.py   (gera os arquivos nesta pasta; determinístico)
"""

import random
from pathlib import Path

AQUI = Path(__file__).parent
rng = random.Random(2026)
COMPRIMENTO = 20000
seq = [rng.choice('ACGT') for _ in range(COMPRIMENTO)]

# Repetição de T para o exemplo de alinhamento à esquerda (posições 15001-15006).
for p in range(15001, 15007):
    seq[p - 1] = 'T'
seq[15000 - 1] = 'A'


def ref(pos):
    return seq[pos - 1]


def outra(base, k=0):
    return [b for b in 'ACGT' if b != base][k]


# (posição, genótipo no chip em letras, genótipo no VCF ou None se sem registro)
casos = []
# 1000..9000: concordantes e discordantes com registro no VCF
for i, pos in enumerate(range(1000, 10000, 1000)):
    r = ref(pos)
    a = outra(r)
    if i % 3 == 0:
        casos.append((pos, r + a, (r, a, '0/1')))           # het igual
    elif i % 3 == 1:
        casos.append((pos, a + a, (r, a, '1/1')))           # hom alt igual
    else:
        casos.append((pos, r + a, (r, a, '1/1')))           # diferença
# sem registro no VCF
casos.append((10500, ref(10500) + outra(ref(10500)), None))   # chip het → só no chip
casos.append((11000, ref(11000) * 2, None))                     # hom = referência (só com FASTA)
casos.append((11500, '--', None))                               # sem chamada
casos.append((12000, '--', (ref(12000), outra(ref(12000)), '0/1')))  # sem chamada × VCF

linhas_vcf = []
for pos, _, v in casos:
    if v:
        linhas_vcf.append((pos, v[0], v[1], v[2]))
# Variante do VCF fora do chip e a deleção na repetição de T
linhas_vcf.append((13000, ref(13000), outra(ref(13000)), '0/1'))
linhas_vcf.append((15005, 'TT', 'T', '0/1'))
linhas_vcf.sort()

vcf = [
    '##fileformat=VCFv4.3',
    '##source=Genoz fixture FICTÍCIA (Módulo 9)',
    '##contig=<ID=1,length=249250621,assembly=GRCh37>',
    '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genótipo">',
    '#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tPESSOA_FICTICIA',
]
for pos, r, a, gt in linhas_vcf:
    vcf.append(f'1\t{pos}\t.\t{r}\t{a}\t60\tPASS\t.\tGT\t{gt}')
(AQUI / 'pessoa_ficticia_grch37.vcf').write_text('\n'.join(vcf) + '\n', encoding='utf-8', newline='
')

chip = [(f'rs{900000 + i}', pos, gt) for i, (pos, gt, _) in enumerate(casos)]
chip.append(('i5000001', 14000, 'DI'))  # indel: ignorado

(AQUI / 'chip_23andme.txt').write_text(
    '# This data file generated by 23andMe (FICTÍCIO, fixture do Genoz)\n'
    '# We are using reference human assembly build 37 (also known as Annotation Release 104).\n'
    '# rsid\tchromosome\tposition\tgenotype\n'
    + ''.join(f'{r}\t1\t{p}\t{g}\n' for r, p, g in chip),
    encoding='utf-8',
    newline='
',
)


def alelos_ancestry(g):
    if g == '--':
        return '0', '0'
    return g[0], g[1]


(AQUI / 'chip_ancestrydna.txt').write_text(
    '#AncestryDNA raw data download (FICTÍCIO, fixture do Genoz)\n'
    '#Genotypes are reported on the forward (+) strand of build 37.1\n'
    'rsid\tchromosome\tposition\tallele1\tallele2\n'
    + ''.join(f'{r}\t1\t{p}\t{a}\t{b}\n' for r, p, g in chip for a, b in [alelos_ancestry(g)]),
    encoding='utf-8',
    newline='
',
)
(AQUI / 'chip_myheritage.csv').write_text(
    '# MyHeritage DNA raw data. (FICTÍCIO, fixture do Genoz)\n'
    '# This file was generated using reference build 37.\n'
    'RSID,CHROMOSOME,POSITION,RESULT\n'
    + ''.join(f'"{r}","1","{p}","{g}"\n' for r, p, g in chip),
    encoding='utf-8',
    newline='
',
)
(AQUI / 'chip_ftdna.csv').write_text(
    'RSID,CHROMOSOME,POSITION,RESULT\n' + ''.join(f'"{r}","1","{p}","{g}"\n' for r, p, g in chip),
    encoding='utf-8',
    newline='
',
)

linhas = [''.join(seq[i:i + 60]) for i in range(0, COMPRIMENTO, 60)]
(AQUI / 'referencia_chr1_trecho.fa').write_text(
    '>1 trecho FICTÍCIO de 20 kb (não é a sequência humana real)\n' + '\n'.join(linhas) + '\n',
    encoding='utf-8',
    newline='
',
)
print('ok:', len(chip), 'sítios de chip,', len(linhas_vcf), 'registros no VCF')
